name: Automated API tests using Postman CLI

on: 
  - push
  - workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl https://dl-cli.pstmn.io/download/latest/linux/ -o postman-cli.tar.gz
          tar -zxvf postman-cli.tar.gz
          sudo mv postman-cli /usr/bin/postman
          rm postman-cli.tar.gz
      - name: Login to Postman CLI
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: postman login --with-api-key $POSTMAN_API_KEY
      - name: Run API tests
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          postman collection run "${GITHUB_WORKSPACE}/postman/collections/VAmPI.json"
          # Run your API using Postman CLI
          postman api lint
