name: Automated API tests using Postman CLI

on: 
  - push
  - workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          # Run your unit/etc tests
          postman collection run "${{ github.workspace }}/postman/collections/VAmPI(1).json" --integration-id "145008-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint "${{ github.workspace }}/postman/schemas/index.yaml" --integration-id 145008
